# Generated by Django 6.0.7 on 2026-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], default='male', max_length=6)),
                ('subjects', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('mern', 'Mern'), ('react', 'React')], max_length=20)),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
